// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bike.Repository;

#nullable disable

namespace bike.Migrations
{
    [DbContext(typeof(BikeDbContext))]
    [Migration("20250804202350_db")]
    partial class db
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("bike.Models.Banner", b =>
                {
                    b.Property<int>("MaBanner")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBanner"));

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LinkLienKet")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaBanner");

                    b.ToTable("Banner");
                });

            modelBuilder.Entity("bike.Models.ChiTietHopDong", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTiet"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("GiaThueNgay")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("MaHopDong")
                        .HasColumnType("int");

                    b.Property<int>("MaXe")
                        .HasColumnType("int");

                    b.Property<string>("MoTaThietHai")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("NgayNhanXe")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTraXeDuKien")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTraXeThucTe")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PhiDenBu")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("SoNgayThue")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TinhTrangTraXe")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThaiXe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaChiTiet");

                    b.HasIndex("MaHopDong");

                    b.HasIndex("MaXe");

                    b.ToTable("ChiTietHopDong");
                });

            modelBuilder.Entity("bike.Models.ChiTieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaXe")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayChi")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("MaXe");

                    b.ToTable("ChiTieu");
                });

            modelBuilder.Entity("bike.Models.DatCho", b =>
                {
                    b.Property<int>("MaDatCho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDatCho"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaUser")
                        .HasColumnType("int");

                    b.Property<int>("MaXe")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayNhanXe")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTraXe")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaDatCho");

                    b.HasIndex("MaUser");

                    b.HasIndex("MaXe");

                    b.ToTable("DatCho");
                });

            modelBuilder.Entity("bike.Models.HinhAnhXe", b =>
                {
                    b.Property<int>("MaHinhAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHinhAnh"));

                    b.Property<bool>("LaAnhChinh")
                        .HasColumnType("bit");

                    b.Property<int>("MaXe")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("NgayThem")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenFile")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("MaHinhAnh");

                    b.HasIndex("MaXe", "LaAnhChinh");

                    b.HasIndex("MaXe", "ThuTu");

                    b.ToTable("HinhAnhXe");
                });

            modelBuilder.Entity("bike.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoaDon"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaHopDong")
                        .HasColumnType("int");

                    b.Property<int?>("MaNguoiTao")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaHopDong")
                        .IsUnique();

                    b.HasIndex("MaNguoiTao");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("bike.Models.HopDong", b =>
                {
                    b.Property<int>("MaHopDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHopDong"));

                    b.Property<string>("BangLaiXe")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CccdMatSau")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CccdMatTruoc")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GiayToKhac")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HoTenKhach")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaDatCho")
                        .HasColumnType("int");

                    b.Property<int?>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<int?>("MaNguoiTao")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayNhanXe")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTraXeDuKien")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTraXeThucTe")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PhuPhi")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("SoCCCD")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<decimal>("TienCoc")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaHopDong");

                    b.HasIndex("MaDatCho");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaNguoiTao");

                    b.ToTable("HopDong");
                });

            modelBuilder.Entity("bike.Models.LoaiXe", b =>
                {
                    b.Property<int>("MaLoaiXe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiXe"));

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenLoaiXe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLoaiXe");

                    b.ToTable("LoaiXe");
                });

            modelBuilder.Entity("bike.Models.Role", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVaiTro"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaVaiTro");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("bike.Models.ThietHai", b =>
                {
                    b.Property<int>("MaThietHai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThietHai"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("LoaiThietHai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaHopDong")
                        .HasColumnType("int");

                    b.Property<int?>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<int?>("MaNguoiBaoCao")
                        .HasColumnType("int");

                    b.Property<int>("MaXe")
                        .HasColumnType("int");

                    b.Property<string>("MoTaThietHai")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHoanThanh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayXayRa")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongAnXuLy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("SoTienDenBu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThaiXuLy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaThietHai");

                    b.HasIndex("MaHopDong");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaNguoiBaoCao");

                    b.HasIndex("MaXe");

                    b.ToTable("ThietHai");
                });

            modelBuilder.Entity("bike.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("MucLuong")
                        .HasColumnType("decimal(18,0)");

                    b.Property<DateTime?>("NgayNghiViec")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayVaoLam")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RoleMaVaiTro")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("RoleMaVaiTro");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("bike.Models.UserPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanCheckout")
                        .HasColumnType("bit");

                    b.Property<bool>("CanCreateBanner")
                        .HasColumnType("bit");

                    b.Property<bool>("CanCreateChiTieu")
                        .HasColumnType("bit");

                    b.Property<bool>("CanCreateHoaDon")
                        .HasColumnType("bit");

                    b.Property<bool>("CanCreateHopDong")
                        .HasColumnType("bit");

                    b.Property<bool>("CanCreateLoaiXe")
                        .HasColumnType("bit");

                    b.Property<bool>("CanCreateNhanVien")
                        .HasColumnType("bit");

                    b.Property<bool>("CanCreateThietHai")
                        .HasColumnType("bit");

                    b.Property<bool>("CanCreateUser")
                        .HasColumnType("bit");

                    b.Property<bool>("CanCreateXe")
                        .HasColumnType("bit");

                    b.Property<bool>("CanDatCho")
                        .HasColumnType("bit");

                    b.Property<bool>("CanDeleteBanner")
                        .HasColumnType("bit");

                    b.Property<bool>("CanDeleteChiTieu")
                        .HasColumnType("bit");

                    b.Property<bool>("CanDeleteHinhAnhXe")
                        .HasColumnType("bit");

                    b.Property<bool>("CanDeleteHoaDon")
                        .HasColumnType("bit");

                    b.Property<bool>("CanDeleteHopDong")
                        .HasColumnType("bit");

                    b.Property<bool>("CanDeleteLoaiXe")
                        .HasColumnType("bit");

                    b.Property<bool>("CanDeleteNhanVien")
                        .HasColumnType("bit");

                    b.Property<bool>("CanDeleteThietHai")
                        .HasColumnType("bit");

                    b.Property<bool>("CanDeleteUser")
                        .HasColumnType("bit");

                    b.Property<bool>("CanDeleteXe")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEditBanner")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEditChiTieu")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEditHinhAnhXe")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEditHoaDon")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEditHopDong")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEditLoaiXe")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEditNhanVien")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEditThietHai")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEditUser")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEditXe")
                        .HasColumnType("bit");

                    b.Property<bool>("CanExportBaoCao")
                        .HasColumnType("bit");

                    b.Property<bool>("CanManageBanner")
                        .HasColumnType("bit");

                    b.Property<bool>("CanManageCart")
                        .HasColumnType("bit");

                    b.Property<bool>("CanManageChiTieu")
                        .HasColumnType("bit");

                    b.Property<bool>("CanManageHinhAnhXe")
                        .HasColumnType("bit");

                    b.Property<bool>("CanManageHoaDon")
                        .HasColumnType("bit");

                    b.Property<bool>("CanManageHopDong")
                        .HasColumnType("bit");

                    b.Property<bool>("CanManageLoaiXe")
                        .HasColumnType("bit");

                    b.Property<bool>("CanManageNhanVien")
                        .HasColumnType("bit");

                    b.Property<bool>("CanManageThietHai")
                        .HasColumnType("bit");

                    b.Property<bool>("CanManageUser")
                        .HasColumnType("bit");

                    b.Property<bool>("CanManageXe")
                        .HasColumnType("bit");

                    b.Property<bool>("CanPrintHoaDon")
                        .HasColumnType("bit");

                    b.Property<bool>("CanPrintHopDong")
                        .HasColumnType("bit");

                    b.Property<bool>("CanThanhToanThietHai")
                        .HasColumnType("bit");

                    b.Property<bool>("CanUploadHinhAnhXe")
                        .HasColumnType("bit");

                    b.Property<bool>("CanViewBanner")
                        .HasColumnType("bit");

                    b.Property<bool>("CanViewBaoCao")
                        .HasColumnType("bit");

                    b.Property<bool>("CanViewCart")
                        .HasColumnType("bit");

                    b.Property<bool>("CanViewChiTieu")
                        .HasColumnType("bit");

                    b.Property<bool>("CanViewDatCho")
                        .HasColumnType("bit");

                    b.Property<bool>("CanViewHinhAnhXe")
                        .HasColumnType("bit");

                    b.Property<bool>("CanViewHoaDon")
                        .HasColumnType("bit");

                    b.Property<bool>("CanViewHopDong")
                        .HasColumnType("bit");

                    b.Property<bool>("CanViewLoaiXe")
                        .HasColumnType("bit");

                    b.Property<bool>("CanViewNhanVien")
                        .HasColumnType("bit");

                    b.Property<bool>("CanViewThietHai")
                        .HasColumnType("bit");

                    b.Property<bool>("CanViewThongKe")
                        .HasColumnType("bit");

                    b.Property<bool>("CanViewUser")
                        .HasColumnType("bit");

                    b.Property<bool>("CanViewXe")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("bike.Models.Xe", b =>
                {
                    b.Property<int>("MaXe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaXe"));

                    b.Property<string>("BienSoXe")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("ChiPhiSuaChua")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("DongXe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("GiaThue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("GiaTriXe")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("HangXe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaLoaiXe")
                        .HasColumnType("int");

                    b.Property<string>("MoTaThietHai")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("NgayGapSuCo")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenXe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaXe");

                    b.HasIndex("MaLoaiXe");

                    b.ToTable("Xe");
                });

            modelBuilder.Entity("bike.Models.ChiTietHopDong", b =>
                {
                    b.HasOne("bike.Models.HopDong", "HopDong")
                        .WithMany("ChiTietHopDong")
                        .HasForeignKey("MaHopDong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bike.Models.Xe", "Xe")
                        .WithMany("ChiTietHopDong")
                        .HasForeignKey("MaXe")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HopDong");

                    b.Navigation("Xe");
                });

            modelBuilder.Entity("bike.Models.ChiTieu", b =>
                {
                    b.HasOne("bike.Models.Xe", "Xe")
                        .WithMany("ChiTieu")
                        .HasForeignKey("MaXe");

                    b.Navigation("Xe");
                });

            modelBuilder.Entity("bike.Models.DatCho", b =>
                {
                    b.HasOne("bike.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("MaUser");

                    b.HasOne("bike.Models.Xe", "Xe")
                        .WithMany()
                        .HasForeignKey("MaXe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Xe");
                });

            modelBuilder.Entity("bike.Models.HinhAnhXe", b =>
                {
                    b.HasOne("bike.Models.Xe", "Xe")
                        .WithMany("HinhAnhXes")
                        .HasForeignKey("MaXe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Xe");
                });

            modelBuilder.Entity("bike.Models.HoaDon", b =>
                {
                    b.HasOne("bike.Models.HopDong", "HopDong")
                        .WithOne("HoaDon")
                        .HasForeignKey("bike.Models.HoaDon", "MaHopDong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bike.Models.User", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("MaNguoiTao")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("HopDong");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("bike.Models.HopDong", b =>
                {
                    b.HasOne("bike.Models.DatCho", "DatCho")
                        .WithMany()
                        .HasForeignKey("MaDatCho");

                    b.HasOne("bike.Models.User", "KhachHang")
                        .WithMany("HopDongKhachHang")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("bike.Models.User", "NguoiTao")
                        .WithMany("HopDongNguoiTao")
                        .HasForeignKey("MaNguoiTao")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DatCho");

                    b.Navigation("KhachHang");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("bike.Models.ThietHai", b =>
                {
                    b.HasOne("bike.Models.HopDong", "HopDong")
                        .WithMany()
                        .HasForeignKey("MaHopDong");

                    b.HasOne("bike.Models.User", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKhachHang");

                    b.HasOne("bike.Models.User", "NguoiBaoCao")
                        .WithMany()
                        .HasForeignKey("MaNguoiBaoCao");

                    b.HasOne("bike.Models.Xe", "Xe")
                        .WithMany()
                        .HasForeignKey("MaXe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HopDong");

                    b.Navigation("KhachHang");

                    b.Navigation("NguoiBaoCao");

                    b.Navigation("Xe");
                });

            modelBuilder.Entity("bike.Models.User", b =>
                {
                    b.HasOne("bike.Models.Role", null)
                        .WithMany("Users")
                        .HasForeignKey("RoleMaVaiTro");
                });

            modelBuilder.Entity("bike.Models.UserPermission", b =>
                {
                    b.HasOne("bike.Models.User", "User")
                        .WithOne("UserPermission")
                        .HasForeignKey("bike.Models.UserPermission", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("bike.Models.Xe", b =>
                {
                    b.HasOne("bike.Models.LoaiXe", "LoaiXe")
                        .WithMany("Xes")
                        .HasForeignKey("MaLoaiXe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiXe");
                });

            modelBuilder.Entity("bike.Models.HopDong", b =>
                {
                    b.Navigation("ChiTietHopDong");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("bike.Models.LoaiXe", b =>
                {
                    b.Navigation("Xes");
                });

            modelBuilder.Entity("bike.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("bike.Models.User", b =>
                {
                    b.Navigation("HopDongKhachHang");

                    b.Navigation("HopDongNguoiTao");

                    b.Navigation("UserPermission");
                });

            modelBuilder.Entity("bike.Models.Xe", b =>
                {
                    b.Navigation("ChiTietHopDong");

                    b.Navigation("ChiTieu");

                    b.Navigation("HinhAnhXes");
                });
#pragma warning restore 612, 618
        }
    }
}
